(() => {
'use strict';
const $=id=>document.getElementById(id);
$('calendar-mount').append(document.querySelector('.lights-panel'));
let letters=[],filter='all',editing=null,mode='listen',turns=[],toastTimer;
try{const saved=JSON.parse(localStorage.getItem('unsent.letters.v1')||'[]');if(Array.isArray(saved))letters=saved.filter(x=>x&&typeof x.id==='string'&&typeof x.body==='string'&&typeof x.title==='string');}catch{notify('无法读取信件，请检查浏览器存储设置');}
function notify(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
function persist(){try{localStorage.setItem('unsent.letters.v1',JSON.stringify(letters));return true;}catch{notify('未能保存到浏览器，关闭后可能丢失');return false;}}
function route(){const key=location.hash.slice(1);const page=['mail','talk','calendar'].includes(key)?key:'talk';document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==page);document.querySelectorAll('[data-page]').forEach(x=>{x.classList.toggle('active',x.dataset.page===page);if(x.dataset.page===page)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});window.scrollTo(0,0);if(page==='mail')renderLetters();}
window.addEventListener('hashchange',route);
function renderLetters(){const list=$('letter-list');list.replaceChildren();$('letter-count').textContent=`${letters.length} 封`;const visible=letters.filter(x=>filter==='all'||x.status===filter).sort((a,b)=>b.updated-a.updated);if(!visible.length){const box=document.createElement('div');box.className='empty-mail';box.textContent=filter==='draft'?'还没有草稿。没写完也没关系，下次再继续。':'这里，收着暂时不必送达的话。写一封信，或从「说说」里把心事收进来。';list.append(box);}for(const letter of visible){const card=document.createElement('button');card.className='letter-card';const meta=document.createElement('small');meta.textContent=`${new Date(letter.updated).toLocaleDateString('zh-CN')} · ${letter.status==='draft'?'草稿':'未寄出'}`;const title=document.createElement('strong');title.textContent=letter.title||'一封没有名字的信';const preview=document.createElement('p');preview.textContent=letter.body;card.append(meta,title,preview);card.addEventListener('click',()=>openLetter(letter));list.append(card);}}
function openLetter(letter=null){editing=letter?.id||null;$('letter-title').value=letter?.title||'';$('letter-body').value=letter?.body||'';$('letter-dialog').showModal();}
function storeLetter(status){const body=$('letter-body').value.trim(),title=$('letter-title').value.trim();if(!body&&!title)return false;const old=letters.find(x=>x.id===editing);const item={id:editing||crypto.randomUUID(),title:title||'给此刻的自己',body,status:old?.status==='saved'?'saved':status,updated:Date.now()};if(old)letters=letters.map(x=>x.id===editing?item:x);else letters.push(item);const success=persist();renderLetters();return success;}
$('new-letter').addEventListener('click',()=>openLetter());$('close-letter').addEventListener('click',()=>{storeLetter('draft');$('letter-dialog').close();});$('letter-dialog').addEventListener('cancel',()=>storeLetter('draft'));
$('letter-form').addEventListener('submit',event=>{event.preventDefault();if(!$('letter-body').value.trim()){notify('先写下一点想留下的话吧');$('letter-body').focus();return;}if(storeLetter('saved'))notify('这封信，已经好好收起来了');$('letter-dialog').close();});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===button);x.setAttribute('aria-pressed',String(x===button));});renderLetters();}));
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>{x.classList.toggle('active',x===button);x.setAttribute('aria-pressed',String(x===button));});}));
function message(text,role){const div=document.createElement('div');div.className=`message ${role}`;div.textContent=text;$('messages').append(div);}
$('chat-form').addEventListener('submit',event=>{event.preventDefault();const text=$('message').value.trim();if(!text)return;turns.push(text);message(text,'user');$('message').value='';const replies={listen:['我在听。你可以接着说，不用急着把这些话整理好。','这段话里，还有什么是你刚才没说出口的？'],comfort:['这一刻不好受，也不需要马上变好。先把这些话留在这里吧。','你不用现在就做决定，我们可以慢一点。'],clarify:['如果这段话真的发出去了，你最希望得到什么回应？','我们可以先分开看看：哪些是已经发生的，哪些是你担心会发生的？']};message(replies[mode][(turns.length-1)%2],'assistant');$('message').focus();$('chat-form').scrollIntoView({block:'nearest'});});
$('save-chat').addEventListener('click',()=>{if(!turns.length){notify('先写下想说的话，再把它收进信箱');$('message').focus();return;}openLetter({title:'那些还没发出去的话',body:turns.join('\n\n')});});$('reset-chat').addEventListener('click',()=>{if(turns.length){notify('请先收好想保留的话；再点一次即可开始新对话');if(!$('reset-chat').dataset.ready){$('reset-chat').dataset.ready='yes';setTimeout(()=>delete $('reset-chat').dataset.ready,4000);return;}}turns=[];$('messages').replaceChildren();message('不用想好开头。\n从你现在最想说的那句话开始吧。','assistant');delete $('reset-chat').dataset.ready;notify('新的对话，慢慢开始');});
route();
})();
